# Generated by Django 5.2.3 on 2025-07-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_post_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
